#!/bin/bash
NC='\033[0m'
args=("$@")
cat << "END_OF_ASCII"

______ _   _ _____ _             _
|  _  | \ | /  ___| |           | |
| | | |  \| \ `--.| | ___   ___ | | ___   _ _ __
| | | | . ` |`--. | |/ _ \ / _ \| |/ | | | | '_ \
| |/ /| |\  /\__/ | | (_) | (_) |   <| |_| | |_) |
|___/ \_| \_\____/|_|\___/ \___/|_|\_\\__,_| .__/
                                           | |
                                           |_|
END_OF_ASCII
if [ "$#" -ne 2 ]; then
        echo -e "\n\e[31m\e[1m[!] Wrong usage of parameters"
        echo -e "\e[1m\e[34m[*] Example usage: ./dnslookup wordlist domain"
else
        echo -e "\e[92m"
        echo "+----------------------------------------------------------------+"
        echo "     Running scan on ${args[1]} using ${args[0]}"
        echo "+----------------------------------------------------------------+"
        echo ""
        echo -e "\e[93m[*] Identified subdomains with records are listed below:"
        echo ""
        cat ${args[0]} | while read list
        do
                dig $list.${args[1]} +noall +answer 2>/dev/null | grep -o $list.${args[1]} | GREP_COLOR='01;33' egrep --color=always $list
        done
echo ""
fi